### ISSUE TITLE
[bug] 本地執行 resend email 功能吃 40101

### ISSUE THREAD

**Issue by qw050123** [erik1110/SuperHandy-backend#11]
我透過 sign up 創建一個帳號後過了兩天，想拿此信件的 token 去做 verify-email 吃到了 [401] 信箱驗證失敗，之後我透過 postman 去打 resend-verification，postman 端吃到了 [40101] 請聯絡管理員，伺服器端報錯如下
Error: connect ETIMEDOUT 2404:6800:4012:3::200d:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -4039,
  code: 'EAUTH',
  syscall: 'connect',
  address: '2404:6800:4012:3::200d',
  port: 443,
  type: 'FETCH',
  sourceUrl: 'https://accounts.google.com/o/oauth2/token',
  command: 'AUTH XOAUTH2'
}
請問是我有誤會什麼嗎~

**Comment by erik1110** [comment]
@qw050123  Hello
- 第一步信箱驗證失敗，這個沒錯，token (JWT_EMAIL_EXPIRES)我提供給你的是1h後過期
- 第二步吃到這個錯誤，應該是寄信的問題，但想請教目前是在哪一個 branch 呢？

**Comment by qw050123** [comment]
中華電信在搞
